# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.1.2
  vulnachecka: whitesource/vulnerability-checker@19.10.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-test:
    executor: 
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      
      - restore_cache:
          key: android-orb-v1-
          
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Run Build
          command: ./gradlew build
      - android/save-gradle-cache
      - android/save-build-cache
      - store_artifacts:
          path: app/build/reports
          destination: app/reports
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: favorites/build/reports
          destination: favorites/reports    
      - android/run-tests:
          test-command: ./gradlew lint test
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
          
  release-build:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - vulnachecka/scan
      - build-test
      - release-build:
          requires:
            - build-test
